name: Installation tests
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x, 18.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.platform }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm link sol2uml --only=production
    - name: KoiosECDSA class
      run: sol2uml class 0x2762e676a9f17c7de34fe4b124424837c7e18e1c -v
      env:
        NODE_URL: ${{ secrets.NODE_URL }}
    - name: KoiosECDSA storage
      run: sol2uml storage 0x2762e676a9f17c7de34fe4b124424837c7e18e1c -v
      env:
        NODE_URL: ${{ secrets.NODE_URL }}
    - name: KoiosECDSA flatten
      run: sol2uml flatten 0x2762e676a9f17c7de34fe4b124424837c7e18e1c -v
      env:
        NODE_URL: ${{ secrets.NODE_URL }}
    - name: Resonate Fantom flatten
      run: sol2uml flatten --network fantom 0x1a5c2ee3fb7fe4a2c2e42474a3657c71f6c775cf -v
      env:
        NODE_URL: ${{ secrets.NODE_URL }}
